; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+17 on Sat Jul 03 2021 15:18:14 GMT+0100 (British Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


