; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+17 on Sat Jul 03 2021 15:18:14 GMT+0100 (British Summer Time)
M280 P0 S10 ; deploy BLTouch

