; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.2.1-LPC+17 on Sat Jul 03 2021 15:18:16 GMT+0100 (British Summer Time)
; Wait for set temperatures to be reached
M116 P0

